version: "3.8"
services:
  backend:
    build:
      context: .
    container_name: fastapi-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: threejs-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    command: python3 -m http.server 8080